AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infraestrutura nativa para API NestJS no Amazon ECS Fargate e Registro de Imagens ECR.'

Parameters:
  AppName:
    Type: String
    Default: nestjs-app
    Description: Nome da aplicacao e identificador de recursos.

Resources:
  # 1. Repositorio Amazon ECR para armazenamento da Imagem Docker
  NestJSECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref AppName
      ImageScanningConfiguration:
        ScanOnPush: true
      Tags:
        - Key: Environment
          Value: Production
        - Key: Project
          Value: NestJS-DevOps

  # 2. Cluster ECS para Orquestracao do Servico Fargate
  NestJSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${AppName}-cluster'
      Tags:
        - Key: Name
          Value: !Sub '${AppName}-ecs-cluster'

  # 3. CloudWatch Log Group para coleta de logs do NestJS
  NestJSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${AppName}'
      RetentionInDays: 7

Outputs:
  ECRRepositoryURL:
    Description: URL do Repositorio Amazon ECR para usar no Docker Push
    Value: !GetAtt NestJSECRRepository.RepositoryUri
    Export:
      Name: !Sub '${AppName}-ECR-URL'

  ECSClusterName:
    Description: Nome do Cluster ECS
    Value: !Ref NestJSCluster
    Export:
      Name: !Sub '${AppName}-Cluster-Name'